### ISSUE TITLE
CLI tool does not work with substition

### ISSUE THREAD

**Issue by lzm0** [puppetlabs/ruby-hocon#135]
## Describe the Bug
Given a file `test.conf`
```hocon
a = yes
b = ${a}
```
and the command
```bash
hocon -i test.conf get b
```
Gives the error
```bash
/opt/homebrew/lib/ruby/gems/3.2.0/gems/hocon-1.4.0/lib/hocon/impl/config_reference.rb:89:in `value_type': need to Config#resolve, see the API docs for Config#resolve; substitution not resolved: ConfigReference(${a}) (Hocon::ConfigError::ConfigNotResolvedError)
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/hocon-1.4.0/lib/hocon/impl/simple_config.rb:297:in `has_path?'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/hocon-1.4.0/lib/hocon/cli.rb:135:in `do_get'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/hocon-1.4.0/lib/hocon/cli.rb:116:in `main'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/hocon-1.4.0/bin/hocon:4:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/hocon:25:in `load'
	from /opt/homebrew/opt/ruby/bin/hocon:25:in `<main>'
```

## Environment
 - Version
   - 1.4.0
 - Platform
   - macOS Ventura 13.5.1
   - ruby 3.2.2

## Additional Context
This should be fixed according to #67. Not sure why it is not working under CLI mode.

**Comment by lzm0** [comment]
The issue is we are using
```Ruby
Hocon::ConfigFactory.parse_string(File.read("test.conf")).get_any_ref("b")
```
